### PR TITLE
Correctly detect vulnerable log4j <2.1

### PR DESCRIPTION
**Pull request by singlethink**
This change correctly detects vulnerable log4j versions <2.1, which do
not contain JndiManager.class, by detecting the presence of
ReflectiveCallerClassUtility.class which was present in all log4j
releases >=2.0-beta9 and <2.1.

### CODE REVIEW

**Comment by nikaiw** [comment]
Would you consider detecting something related to the vulnerability instead such as the presence "javax.naming.InitialContext" in jndilookup ?
E.g: https://github.com/nikaiw/log4jscanner/blob/0def0d6a7ba714dbcfd1565a2954290948d2f062/jar/jar.go#L328

**Comment by singlethink** [comment]
Sure

**Comment by singlethink** [comment]
Done

**Comment by ericchiang** [comment]
@ddworken mind taking a look at this one?

**Review by ddworken — APPROVED** [review]
Thank you for the change!

**Pull request merged**
